SELECT
    SUS.US_NOME,
    SUS.US_CGC,
    SUS.US_MUN,
    SUS.US_EST, 
    SUS.US_DDD, 
    SUS.US_TEL, 
    SUS.US_EMAIL,
    SUS.US_DTCAD,
    SUS.US_STATUS,
    SUS.US_VEND,  
    SUS.US_X_MOTI,
    SUS.US_X_TRAV
FROM SUS010 SUS
WHERE SUS.D_E_L_E_T_ = ''
  AND SUS.US_VEND NOT IN ('000000', '')